name: mkxref-dev
channels:
  - conda-forge

dependencies:
  # runtime
  - python >=3.8,<3.12
  - mkdocstrings-python >=1.5.2,<2.0
  # test
  - coverage >=7.3.0
  - pytest >=7.4.0
  - pytest-cov >=4.1.0
  - pylint >=2.17.5
  - mypy >=1.5.1
  - mkdocs-material >=8.2
  - beautifulsoup4 >=4.12
  # documentation
  - black
  - mkdocs >=1.3.0
  - pymdown-extensions
  - mkdocs-material >=8.2
  - linkchecker >=10.2.1
