name: mkxref-dev
channels:
  - conda-forge

dependencies:
  # runtime
  - python >=3.8,<3.13
  - mkdocstrings-python >=1.5.2,<2.0
  # build
  - hatchling >=1.18
  # test
  - coverage >=7.3.0
  - pytest >=7.4.0
  - pytest-cov >=4.1.0
  - pylint >=2.17.5
  - mypy >=1.5.1
  - mkdocs-material >=8.2
  - beautifulsoup4 >=4.12
  # documentation
  - black >=23.7
  - mike >=1.1,<2.0
  - mkdocs >=1.5.0,<2.0
  - mkdocs-material >=9.1
  - linkchecker >=10.2.1
