name: mkxref-dev
channels:
  - conda-forge

dependencies:
  # runtime
  - python >=3.8,<3.13
  - mkdocstrings-python >=1.6.2,<1.10 # TODO: issue #18
  # build
  - build >=0.7.0
  - hatchling >=1.21
  # test
  - coverage >=7.4.0
  - pytest >=7.4.0
  - pytest-cov >=4.1.0
  - pylint >=3.0.3
  - mypy >=1.8
  - beautifulsoup4 >=4.12
  # documentation
  - black >=23.12
  - mike >=1.1,<2.0
  - mkdocs >=1.5.3,<2.0
  - mkdocs-material >=9.5.4
  - linkchecker >=10.4
