site_name: "mkdocstrings-python-xref"
site_description: "A an extended Python handler for mkdocstrings."
repo_url: https://github.com/analog-garage/mkdocstrings-python-xref
site_url: https://github.com/analog-garage/mkdocstrings-python-xref
repo_name: GitHub
site_dir: site
site_author: Christopher Barber
copyright: Copyright &copy; 2022-2023  Analog Devices, Inc.

watch:
  - src/mkdocstrings_handlers

nav:
- User Guide: relative-crossref.md
- Setup:
    - Installation: install.md
    - Configuration: config.md
- Support:
  - Getting help: support.md
  - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  logo: logo.svg
  favicon: logo.svg
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra:
  generator: false
  version:
    provider: mike
    default: stable

markdown_extensions:
- admonition
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

plugins:
- search
- mike:
    # These fields are all optional; the defaults are as below...
    canonical_version: stable
    version_selector: true
    css_dir: css
    javascript_dir: js
- mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        paths: [src]
        import:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/objects.inv
        - https://mkdocstrings.github.io/griffe/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          relative_crossrefs: yes
          separate_signature: yes
          show_source: no
          show_root_full_path: no

