site_name: "garpy.mkdocstrings"
site_description: "A an extened Python handler for mkdocstrings."
repo_url: https://gitlab.analog.com/boston-garage/garpy.mkdocstrings
site_url: https://gitlab.analog.com/boston-garage/garpy.mkdocstrings
repo_name: GitLab
site_dir: site
site_author: Christopher Barber
copyright: Copyright &copy; 2022  Analog Devices, Inc.

watch:
  - src/mkdocstrings_handlers

nav:
- User Guide:
    - Overview: index.md
    - Relative cross-references: relative-crossref.md
- Setup:
    - Installation: install.md
    - Configuration: config.md
- Support:
  - Getting help: support.md
  - Changelog: changelog.md
  - License: license.md

theme:
  name: material
  logo: garpy.mkdocstrings.svg
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://cto-adi.slack.com/archives/C8ZQJ9DA4
      name: "#ag-software in the CTO ADI workspace"

plugins:
- search
- mkdocstrings:
    default_handler: garpy_python
    handlers:
      garpy_python:
        paths: [src]
        import:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/objects.inv
        - https://mkdocstrings.github.io/griffe/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          relative_crossrefs: yes
          separate_signature: yes
          show_source: no
          show_root_full_path: no

