{% set data = load_file_data('conda-meta-data.json') %}

package:
  name: garpy.mkdocstrings
  version: {{ data['version'] }}

source:
  - path: ../pyproject.toml
  - path: ../conda-meta-data.json
  - path: ../runtime-env.yml
  - path: ../LICENSE.md
  - path: ../src
    folder: src
  - path: ../tests
    folder: tests

build:
  noarch: python
  script: pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python 3.8
    - hatch-garconda >=0.2.4

  run:
    - python {{ data['requires-python'] }}

    {% for dep in data['conda-dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}



test:
  source_files:
    - tests
  requires:
    - pytest >=7.4
    - beautifulsoup4 >=4.12
    - mkdocs-material >=8.2
  imports:
    - mkdocstrings_handlers.garpy_python
  commands:
    - pytest tests

about:
  description: {{ data['description']}}
